@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
participant "Client Application" as Client
actor User
box Service
boundary Server
control ServerRunnable <<Runnable>>
control Master
control MapNode
control ReduceNode
control MapWorker
control ReduceWorker
control ReduceWorkerRunnable <<Runnable>>
collections MemCache
end box
database Mongo
boundary "Google Geolocation API" as GGA
autonumber "<b>[000]"

== Initialization ==

User -> ReduceWorker : Initializes
activate ReduceWorker

ReduceWorker -> ReduceWorker : Opens Server Socket

User -> MapWorker : Initializes
activate MapWorker

MapWorker -> MapWorker : Opens Server Socket

User -> Server: Initializes
activate Server

Server -> Master : Initializes
activate Master

Master -> MemCache : Initializes
activate MemCache

Master -> MapNode : Initializes
activate MapNode

Master -> ReduceNode : Initializes
activate ReduceNode

MapNode -> MapWorker : Opens socket

MapWorker -> MapWorker : Accepts connection

ReduceNode -> ReduceWorker : Opens socket

ReduceWorker -> ReduceWorkerRunnable : Accepts connection
activate ReduceWorkerRunnable

Server -> Server : Opens Server Socket

== Runtime ==

Client -> Server : Connects

Server -> ServerRunnable : Accepts Connection
activate ServerRunnable

alt Search Directions

Client -> ServerRunnable : Query for Directions

ServerRunnable -> Master : Query for Directions

Master -> MemCache : Query for Directions

alt Cache Hit

MemCache --> Master : Returns Result

else Cache Miss

Master -> MapNode : Distributes Query to MapWorkers

MapNode -> MapWorker : Distribute Query to MapWorkers

Master -> Master : Waits for MapWorkers

MapWorker -> MapWorker : Processes Request

MapWorker -> ReduceWorkerRunnable : Reduce Result
activate ReduceWorkerRunnable

ReduceWorkerRunnable -> ReduceWorkerRunnable : Reduces Result

MapWorker -> ReduceWorkerRunnable : Sends Exit Signal
deactivate ReduceWorkerRunnable

MapWorker --> Master : Sends Acknowledgement

Master -> ReduceWorkerRunnable : Sends Acknowledgement

alt Map-Reduce Hit

ReduceWorkerRunnable --> Master : Returns Reduced Result

Master -> Master : Calculates Euclidean Minimum

else Map-Reduce Miss

Master -> GGA : Queries For Directions

GGA --> Master : Returns Result

Master -> MemCache : Saves Result

Master -> Mongo : Saves Result

end

end

Master --> ServerRunnable : Sends Result

ServerRunnable --> Client : Sends Result

else Exit Signal

Client -> ServerRunnable : Sends Exit Signal
deactivate ServerRunnable

== Shutdown ==

else Terminate Signal

Client -> ServerRunnable : Sends Terminate Signal

ServerRunnable -> Master : Terminates Master

Master -> MapNode : Terminates MapNode

Master -> ReduceNode : Terminates ReduceNode

MapNode -> MapWorker : Sends Exit Signal
deactivate MapWorker

ReduceNode -> ReduceWorkerRunnable : Sends Terminate Signal

ReduceWorkerRunnable -> ReduceWorker : Closes Server Socket

deactivate ReduceWorkerRunnable
deactivate ReduceWorker

deactivate ReduceNode
deactivate MapNode
deactivate MemCache
deactivate Master

deactivate ServerRunnable

deactivate Server

end


@enduml