@startuml
participant "Client Application" as Client
actor User
boundary Server
control ServerRunnable
control Master
control MapNode
control ReduceNode
control MapWorker
control ReduceWorker
control ReduceWorkerRunnable
collections MemCache
database Mongo
boundary "Google Geolocation API" as GGA
autonumber "<b>[000]"

== Initialization ==

User -> ReduceWorker : Initializes
activate ReduceWorker

ReduceWorker -> ReduceWorker : Opens Server Socket

User -> MapWorker : Initializes
activate MapWorker

MapWorker -> MapWorker : Opens Server Socket

User -> Server: Initializes
activate Server

Server -> Master : Initializes
activate Master

Master -> MemCache : Initializes
activate MemCache

Master -> MapNode : Initializes
activate MapNode

Master -> ReduceNode : Initializes
activate ReduceNode

MapNode -> MapWorker : Opens socket

MapWorker -> MapWorker : Accepts connection

ReduceNode -> ReduceWorker : Opens socket

ReduceWorker -> ReduceWorkerRunnable : Accepts connection
activate ReduceWorkerRunnable

Server -> Server : Opens Server Socket

== Runtime ==

Client -> Server : Connects

Server -> ServerRunnable : Accepts Connection
activate ServerRunnable

alt Search Directions

Client -> ServerRunnable : Query for Directions

ServerRunnable -> Master : Query for Directions

Master -> MemCache : Query for Directions

alt Hit

MemCache -> Master : Returns Result

else Miss

Master -> MapWorker : Distribute Query to MapWorker

Master -> Master : Waits for MapWorkers

MapWorker -> MapWorker : Processes Request

MapWorker -> ReduceWorkerRunnable : Reduce Result
activate ReduceWorkerRunnable

ReduceWorkerRunnable -> ReduceWorkerRunnable : Reduces Result

MapWorker -> ReduceWorkerRunnable : Sends Exit Signal
deactivate ReduceWorkerRunnable

MapWorker -> Master : Sends Acknowledgement

Master -> ReduceWorkerRunnable : Sends Acknowledgement

alt Hit

ReduceWorkerRunnable -> Master : Returns Reduced Result

Master -> Master : Calculates Euclidean Minimum

else Miss

Master -> GGA : Queries For Directions

GGA --> Master : Returns Result

Master -> MemCache : Saves Result

Master -> Mongo : Saves Result

end

end

Master -> ServerRunnable : Sends Result

ServerRunnable -> Client : Sends Result

else Exit Signal

Client -> ServerRunnable : Sends Exit Signal
deactivate ServerRunnable

== Shutdown ==

else Terminate Signal

Client -> ServerRunnable : Sends Terminate Signal
deactivate ServerRunnable

deactivate Master

deactivate Server

end


@enduml